# Generated by Django 6.0.5 on 2026-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_us', models.CharField(max_length=16)),
                ('contr_us', models.CharField(max_length=16)),
            ],
        ),
    ]
