# Generated by Django 6.0.5 on 2026-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contr_us',
            field=models.CharField(max_length=50),
        ),
    ]
